apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack-service-account
  namespace: kpack
secrets:
  - name: docker-credentials
  - name: github-creds
imagePullSecrets:
  - name: docker-credentials

