apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: builder
  namespace: default
spec:
  serviceAccountName: kpack-service-account
  tag: frederikpietzko/java-builder
  stack:
    name: base
    kind: ClusterStack
  store:
    name: cluster-store
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/nodejs
